# poetry export --without-hashes --output requirements.txt
# poetry export --dev --without-hashes --output requirements-dev.txt

name: default
kind: pipeline

steps:
- name: test
  image: ubuntu
  environment:
    AUTORADARR_DB_HOST: 
      from_secret: AUTORADARR_DB_HOST
    AUTORADARR_DB_USERNAME: 
      from_secret: AUTORADARR_DB_USERNAME
    AUTORADARR_DB_PASSWORD:
      from_secret: AUTORADARR_DB_PASSWORD
    IMDB_APIKEY:
      from_secret: IMDB_APIKEY
    RADARR_APIKEY: 
      from_secret: RADARR_APIKEY
    RADARR_DEFAULT_QUALITY:
      from_secret: RADARR_DEFAULT_QUALITY
    RADARR_ROOT_ANIMATIONS: 
      from_secret: RADARR_ROOT_ANIMATIONS
    RADARR_ROOT_OTHER:
      from_secret: RADARR_ROOT_OTHER
    RADARR_URL: 
      from_secret: RADARR_URL
    TMDB_APIKEY: 
      from_secret: TMDB_APIKEY
  commands:
  - sudo apt install net-tools
  - ifconfig -a
  - ping -c 3 172.19.0.2
  #- /usr/local/bin/python -m pip install --upgrade pip
  #- pip install -r requirements-dev.txt
  #- pytest
