version: '3.8'
services:
  database:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: admin
      DB_NAME: autoradarr
      DB_USER: "${AUTORADARR_DB_USERNAME}"
      DB_PASSWORD: "${AUTORADARR_DB_PASSWORD}"
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongodbdata:/data/db
    ports:
      - 27017:27017
    restart: always
volumes: 
  mongodbdata:
