version: '3.8'
services:
  database:
    container_name: autoradarr
    image: miheevv/autoradarr:latest
    environment:
      AUTORADARR_DB_HOST: "${AUTORADARR_DB_HOST}"
      AUTORADARR_DB_USERNAME: "${AUTORADARR_DB_USERNAME}"
      AUTORADARR_DB_PASSWORD: "${AUTORADARR_DB_PASSWORD}"
      IMDB_APIKEY: "${IMDB_APIKEY}"
      RADARR_APIKEY: "${RADARR_APIKEY}"
      RADARR_DEFAULT_QUALITY: "${RADARR_DEFAULT_QUALITY}"
      RADARR_ROOT_ANIMATIONS: "${RADARR_ROOT_ANIMATIONS}"
      RADARR_ROOT_OTHER: "${RADARR_ROOT_OTHER}"
      RADARR_URL: "${RADARR_URL}"
      TMDB_APIKEY: "${TMDB_APIKEY}"
    # restart: always
